services:
  - type: web
    name: cshub
    runtime: python
    buildCommand: "python -m pip install -r requirements.txt && python manage.py collectstatic --noinput --no-post-process"
    startCommand: "python manage.py fix_permissions; python manage.py migrate --noinput; python manage.py reset_passwords; gunicorn gestao_reclame_aqui.wsgi:application --workers 2 --threads 2 --worker-class gthread --worker-tmp-dir /dev/shm --timeout 120 --graceful-timeout 30 --max-requests 1000 --max-requests-jitter 100"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

      - key: ALLOWED_HOSTS
        value: "cshub-deploy.onrender.com,cshub-l8jg.onrender.com,.onrender.com"
      - key: DB_NAME
        value: "defaultdb"
      - key: DB_USER
        value: "jeferson"
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        value: "ageing-phantom-12866.jxf.gcp-southamerica-east1.cockroachlabs.cloud"
      - key: DB_PORT
        value: "26257"
