services:
  - type: web
    name: cshub
    runtime: python
    buildCommand: "python -m pip install -r requirements.txt && python manage.py collectstatic --noinput --no-post-process"
    startCommand: "uvicorn gestao_reclame_aqui.asgi:application --host 0.0.0.0 --port 10000 --workers 1"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "cshub-deploy.onrender.com,cshub-l8jg.onrender.com,.onrender.com"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
