services:
  - type: web
    name: cshub
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python manage.py migrate && daphne -b 0.0.0.0 -p $PORT gestao_reclame_aqui.asgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "cshub-deploy.onrender.com,cshub-l8jg.onrender.com,.onrender.com"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
