# Generated by Django 5.0.1 on 2025-11-13 16:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('analista', 'Analista'), ('gestor', 'Gestor')], default='analista', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Criar'), ('update', 'Atualizar'), ('delete', 'Excluir'), ('login', 'Login'), ('logout', 'Logout'), ('password_reset', 'Reset de Senha'), ('status_change', 'Mudança de Status')], max_length=20)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('detalhes_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ra', models.CharField(max_length=100, unique=True)),
                ('cpf_cliente', models.CharField(max_length=11)),
                ('nome_cliente', models.CharField(max_length=200)),
                ('sobrenome', models.CharField(blank=True, max_length=200)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('loja_cod', models.CharField(max_length=50)),
                ('unidade_codigo', models.CharField(blank=True, max_length=50)),
                ('origem_contato', models.CharField(choices=[('RA', 'Reclame Aqui'), ('Telefone', 'Telefone'), ('Email', 'Email'), ('WhatsApp', 'WhatsApp'), ('Outro', 'Outro')], max_length=20)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('aguardando_avaliacao', 'Aguardando Avaliação'), ('resolvido', 'Resolvido')], default='pendente', max_length=20)),
                ('data_reclamacao', models.DateField(blank=True, null=True)),
                ('data_resposta', models.DateField(blank=True, null=True)),
                ('nota_satisfacao', models.IntegerField(blank=True, null=True)),
                ('feedback_text', models.TextField(blank=True)),
                ('repeticoes_count', models.IntegerField(default=0)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('tipo_interacao', models.CharField(choices=[('criacao', 'Criação'), ('atualizacao', 'Atualização'), ('resposta_cliente', 'Resposta ao Cliente'), ('mudanca_status', 'Mudança de Status'), ('avaliacao', 'Avaliação'), ('comentario_interno', 'Comentário Interno'), ('anexo_adicionado', 'Anexo Adicionado')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.complaint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['cpf_cliente'], name='core_compla_cpf_cli_1b4907_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['id_ra'], name='core_compla_id_ra_66caac_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['email_cliente'], name='core_compla_email_c_1afb18_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['loja_cod'], name='core_compla_loja_co_f563fd_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['analista'], name='core_compla_analist_468088_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status'], name='core_compla_status_5d4f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['created_at'], name='core_compla_created_f58568_idx'),
        ),
    ]
