# Generated by Django 5.0.1 on 2025-11-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='cpf_cliente',
            field=models.CharField(max_length=14),
        ),
    ]
