# Generated by Django 5.0.1 on 2025-11-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_complaint_cpf_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='unidade_codigo',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('em_replica', 'Em Réplica'), ('aguardando_avaliacao', 'Aguardando Avaliação'), ('resolvido', 'Resolvido')], default='pendente', max_length=20),
        ),
    ]
