# Generated by Django 5.0.1 on 2025-11-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_complaint_data_reclamacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='tipo_reclamacao',
            field=models.CharField(blank=True, choices=[('nota_fiscal', 'Nota fiscal'), ('pagamento_cartao', 'Pagamento não processado - Cartão'), ('pagamento_pix', 'Pagamento não processado - PIX'), ('pagamento_checkout', 'Pagamento não processado - Checkout Web'), ('assinatura_mensal', 'Assinatura mensal'), ('lavagem', 'Lavagem'), ('secagem', 'Secagem'), ('atendimento', 'Atendimento'), ('sistema_totem', 'Sistema/Totem'), ('cupons', 'Cupons'), ('outros', 'Outros')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='volta_fazer_negocio',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não'), ('nao_informado', 'Não informado')], max_length=20, null=True),
        ),
    ]
