# Generated by Django 5.0.1 on 2026-01-07 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_department_alter_user_role_complaint_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=50)),
                ('cor', models.CharField(default='#2563eb', max_length=20)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='AnalistaEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('pausa', models.CharField(blank=True, max_length=50)),
                ('data_primeira_folga', models.DateField(blank=True, null=True)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('turno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analistas', to='core.turno')),
            ],
            options={
                'ordering': ['turno__ordem', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='FolgaManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('folga', 'Folga'), ('ferias', 'Férias'), ('atestado', 'Atestado'), ('trabalho', 'Trabalho')], max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folgas_manuais', to='core.analistaescala')),
            ],
            options={
                'ordering': ['data'],
                'unique_together': {('analista', 'data')},
            },
        ),
    ]
