# Generated by Django 5.0.1 on 2026-01-07 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_turno_analistaescala_folgamanual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField()),
                ('horario', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo', models.CharField(choices=[('agendamento', 'Agendamento'), ('reuniao', 'Reunião'), ('visita', 'Visita'), ('outro', 'Outro')], default='agendamento', max_length=20)),
                ('codigo_loja', models.CharField(blank=True, max_length=50, null=True)),
                ('analista_nome', models.CharField(blank=True, max_length=200, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.department')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data_inicio', 'horario'],
            },
        ),
    ]
