# Generated by Django 5.0.1 on 2026-01-07 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='FerramentaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(default='ia', max_length=100)),
            ],
            options={
                'verbose_name': 'Ferramenta de IA',
                'verbose_name_plural': 'Ferramentas de IA',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='ArtigoBaseConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('categoria', models.CharField(choices=[('tutorials', 'Tutoriais e Guias'), ('solutions', 'Soluções Comuns'), ('faq', 'Perguntas Frequentes')], default='tutorials', max_length=20)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos_kb', to='core.department')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos_kb_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artigo da Base de Conhecimento',
                'verbose_name_plural': 'Artigos da Base de Conhecimento',
                'ordering': ['-views', '-created_at'],
            },
        ),
    ]
