# Generated by Django 5.0.1 on 2026-01-07 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ferramentaia_artigobaseconhecimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacaoDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('texto', models.TextField()),
                ('tipo', models.CharField(choices=[('feedback', 'Feedback'), ('evento', 'Evento'), ('treinamento', 'Treinamento'), ('elogio', 'Elogio'), ('alerta', 'Alerta')], default='feedback', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observacoes_desempenho', to=settings.AUTH_USER_MODEL)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observacoes_desempenho', to='core.department')),
            ],
            options={
                'verbose_name': 'Observação de Desempenho',
                'verbose_name_plural': 'Observações de Desempenho',
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndicadorDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nps', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('tme', models.IntegerField(blank=True, null=True)),
                ('chats', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_desempenho', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_desempenho', to='core.department')),
            ],
            options={
                'verbose_name': 'Indicador de Desempenho',
                'verbose_name_plural': 'Indicadores de Desempenho',
                'ordering': ['-data'],
                'unique_together': {('analista', 'data')},
            },
        ),
    ]
