# Generated by Django 5.0.1 on 2026-01-07 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_store_cartao_checklists_cartao_cover_color_escala'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='membros',
            field=models.ManyToManyField(blank=True, related_name='cartoes_membro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CartaoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='quadro_anexos/%Y/%m/')),
                ('nome_original', models.CharField(max_length=255)),
                ('tipo_arquivo', models.CharField(blank=True, max_length=100)),
                ('tamanho', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.cartao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_cartao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CartaoComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.cartao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_cartao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuadroEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas_quadro', to='core.department')),
            ],
            options={
                'verbose_name': 'Etiqueta do Quadro',
                'verbose_name_plural': 'Etiquetas do Quadro',
            },
        ),
        migrations.AddField(
            model_name='cartao',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='cartoes', to='core.quadroetiqueta'),
        ),
    ]
