# Generated by Django 5.0.1 on 2026-01-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cartao_membros_cartaoanexo_cartaocomentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lista',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
