# Generated by Django 5.0.1 on 2026-01-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cartao_archived_lista_archived'),
    ]

    operations = [
        # Primeiro adicionar os novos campos
        migrations.AddField(
            model_name='indicadordesempenho',
            name='ano',
            field=models.IntegerField(default=2026),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicadordesempenho',
            name='mes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        # Depois remover a constraint antiga (que usa 'data')
        migrations.AlterUniqueTogether(
            name='indicadordesempenho',
            unique_together=set(),
        ),
        # Agora remover o campo data
        migrations.RemoveField(
            model_name='indicadordesempenho',
            name='data',
        ),
        # Agora criar a nova constraint e meta options
        migrations.AlterUniqueTogether(
            name='indicadordesempenho',
            unique_together={('analista', 'mes', 'ano')},
        ),
        migrations.AlterModelOptions(
            name='indicadordesempenho',
            options={'ordering': ['-ano', '-mes'], 'verbose_name': 'Indicador de Desempenho', 'verbose_name_plural': 'Indicadores de Desempenho'},
        ),
    ]
