# Generated by Django 5.0.1 on 2026-01-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_routine_task_routinelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
