# Generated by Django 5.0.1 on 2026-01-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_routine_notified_task_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='time_limit',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routinelog',
            name='warning_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='warning_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
