# Generated by Django 5.0.1 on 2026-01-09 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_routine_time_limit_routinelog_warning_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_code', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_cpf', models.CharField(max_length=14)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('incident_date', models.DateField()),
                ('purchase_location', models.CharField(choices=[('loja_fisica', 'Loja Física'), ('site', 'Site')], max_length=20)),
                ('reason', models.TextField()),
                ('checked_cameras', models.BooleanField(default=False)),
                ('refund_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_type', models.CharField(choices=[('pix', 'PIX'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('checkout_web', 'Checkout Web (Site)'), ('saldo_lavanderia', 'Estorno para Saldo da Lavanderia')], max_length=30)),
                ('pix_key', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField()),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_analise', 'Em Análise'), ('concluida', 'Concluída')], default='aberta', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notified_cs', models.BooleanField(default=False)),
                ('notified_nrs_completion', models.BooleanField(default=False)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='refund_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('refund_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.refundrequest')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
