# Generated by Django 5.0.1 on 2026-01-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_refundrequest_cancellation_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
