# Generated by Django 5.0.1 on 2026-01-10 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_refundrequest_cancellation_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_audits', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='core.store')),
            ],
            options={
                'verbose_name': 'Auditoria de Loja',
                'verbose_name_plural': 'Auditorias de Lojas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreAuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(choices=[('cameras', 'Câmeras'), ('estofados', 'Estofados'), ('cestos_medidas', 'Cestos de medidas'), ('layout', 'Layout'), ('tv', 'TV'), ('totem', 'Totem'), ('limpeza', 'Limpeza da loja'), ('marketing', 'Marketing')], max_length=50)),
                ('is_compliant', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='audit_photos/')),
                ('description', models.TextField(blank=True, help_text='Observações sobre a irregularidade')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.storeaudit')),
            ],
        ),
        migrations.CreateModel(
            name='StoreAuditIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestor_notes', models.TextField(blank=True, verbose_name='Notas do Gestor')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('resolvida', 'Resolvida')], default='aberta', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_audit_issues', to=settings.AUTH_USER_MODEL)),
                ('audit_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='core.storeaudititem')),
            ],
            options={
                'verbose_name': 'Pendência de Auditoria',
                'verbose_name_plural': 'Pendências de Auditoria',
                'ordering': ['-created_at'],
            },
        ),
    ]
