# Generated by Django 5.0.1 on 2026-01-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_storeaudit_storeaudititem_storeauditissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeauditissue',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
