# Generated by Django 5.0.1 on 2026-01-10 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_storeauditissue_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeauditissue',
            name='audit_item',
        ),
        migrations.AddField(
            model_name='storeauditissue',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_issues', to='core.store'),
        ),
        migrations.AddField(
            model_name='storeaudititem',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.storeauditissue'),
        ),
    ]
