# Generated by Django 5.0.1 on 2026-01-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_chat_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadordesempenho',
            name='meta_chats',
            field=models.IntegerField(blank=True, help_text='Meta de quantidade de chats', null=True),
        ),
        migrations.AddField(
            model_name='indicadordesempenho',
            name='meta_nps',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Meta de NPS', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='indicadordesempenho',
            name='meta_tme',
            field=models.IntegerField(blank=True, help_text='Meta de TME em segundos', null=True),
        ),
    ]
