# Generated by Django 5.0.1 on 2026-01-12 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_meta_fields_to_indicador'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaMensalGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('meta_tme', models.IntegerField(blank=True, help_text='Meta global de TME em segundos', null=True)),
                ('meta_nps', models.DecimalField(blank=True, decimal_places=2, help_text='Meta global de NPS', max_digits=4, null=True)),
                ('meta_chats', models.IntegerField(blank=True, help_text='Meta global de quantidade de chats', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_globais', to='core.department')),
            ],
            options={
                'verbose_name': 'Meta Mensal Global',
                'verbose_name_plural': 'Metas Mensais Globais',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('mes', 'ano', 'department')},
            },
        ),
    ]
