# Generated by Django 5.0.1 on 2026-01-12 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_create_meta_mensal_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='StoreViewerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('is_auditing', models.BooleanField(default=False, help_text='True if user is actively auditing, not just viewing')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_sessions', to='core.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_viewer_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de Visualização de Loja',
                'verbose_name_plural': 'Sessões de Visualização de Lojas',
                'unique_together': {('store', 'user')},
            },
        ),
    ]
