# Generated by Django 5.0.1 on 2026-01-15 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_kanban_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='analistaescala',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escala_perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analistaescala',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analistas', to='core.turno'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='origem_contato',
            field=models.CharField(choices=[('RA', 'Reclame Aqui'), ('Telefone', 'Telefone'), ('Email', 'Email'), ('WhatsApp', 'WhatsApp'), ('Outro', 'Outro')], default='RA', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='tipo_reclamacao',
            field=models.CharField(choices=[('nota_fiscal', 'Nota fiscal'), ('pagamento_cartao', 'Pagamento não processado - Cartão'), ('pagamento_pix', 'Pagamento não processado - PIX'), ('pagamento_checkout', 'Pagamento não processado - Checkout Web'), ('assinatura_mensal', 'Assinatura mensal'), ('lavagem', 'Lavagem'), ('secagem', 'Secagem'), ('atendimento', 'Atendimento'), ('sistema_totem', 'Sistema/Totem'), ('cupons', 'Cupons'), ('outros', 'Outros')], default='', max_length=30),
            preserve_default=False,
        ),
    ]
