# Generated by Django 5.0.1 on 2026-01-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_analistaescala_user_alter_analistaescala_turno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tutorial_visto',
            field=models.BooleanField(default=False),
        ),
    ]
