# Generated by Django 5.0.1 on 2026-01-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_user_tutorial_visto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tutorial_visto',
        ),
        migrations.AlterField(
            model_name='artigobaseconhecimento',
            name='categoria',
            field=models.CharField(choices=[('tutorials', 'Tutoriais e Guias'), ('solutions', 'Soluções Comuns'), ('faq', 'Perguntas Frequentes'), ('troubleshooting', 'Resolução de Problemas')], default='tutorials', max_length=20),
        ),
    ]
