# Generated by Django 5.0.1 on 2026-01-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_user_tutorial_visto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigobaseconhecimento',
            name='categoria',
            field=models.CharField(choices=[('tutorials', 'Tutoriais e Guias'), ('solutions', 'Soluções Comuns'), ('faq', 'Perguntas Frequentes'), ('troubleshooting', 'Resolução de Problemas'), ('training', 'Treinamentos')], default='tutorials', max_length=20),
        ),
    ]
