# Generated by Django 5.0.1 on 2026-01-17 01:13

from django.db import migrations

def migrate_to_training(apps, schema_editor):
    ArtigoBaseConhecimento = apps.get_model('core', 'ArtigoBaseConhecimento')
    
    titles = [
        "Módulo 3 – O Totem",
        "MÓDULO 4 – REDES (MIKROTIK)"
    ]
    
    for title in titles:
        # Tenta encontrar por título exato ou aproximado
        articles = ArtigoBaseConhecimento.objects.filter(titulo__iexact=title)
        if not articles.exists():
            # Tenta encontrar pelos primeiros caracteres
            articles = ArtigoBaseConhecimento.objects.filter(titulo__istartswith=title[:10])
            
        for article in articles:
            article.categoria = 'training'
            article.save()

def reverse_migration(apps, schema_editor):
    # Reverte para troubleshooting
    ArtigoBaseConhecimento = apps.get_model('core', 'ArtigoBaseConhecimento')
    ArtigoBaseConhecimento.objects.filter(categoria='training').update(categoria='troubleshooting')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_artigobaseconhecimento_categoria'),
    ]

    operations = [
        migrations.RunPython(migrate_to_training, reverse_migration),
    ]
