# Generated by Django 5.0.1 on 2026-01-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_move_articles_to_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='incident_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
