# Generated by Django 5.0.1 on 2026-01-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_refundrequest_incident_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='last_audit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Última Auditoria'),
        ),
        migrations.AddField(
            model_name='store',
            name='last_audit_result',
            field=models.CharField(choices=[('pending', 'Pendente'), ('conforme', 'Conforme'), ('irregular', 'Irregular')], default='pending', max_length=20, verbose_name='Resultado da Última Auditoria'),
        ),
        migrations.AddField(
            model_name='store',
            name='needs_reverification',
            field=models.BooleanField(default=False, verbose_name='Precisa Reverificação'),
        ),
        migrations.AddField(
            model_name='storeauditissue',
            name='notification_channel',
            field=models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('notificacao', 'Notificação/Email'), ('ticket', 'Ticket'), ('telefone', 'Telefone'), ('presencial', 'Presencial')], max_length=20, verbose_name='Canal de Notificação'),
        ),
        migrations.AddField(
            model_name='storeauditissue',
            name='resolution_history',
            field=models.JSONField(blank=True, default=list, verbose_name='Histórico de Resolução'),
        ),
        migrations.AddField(
            model_name='storeauditissue',
            name='resolution_stage',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_contato', 'Em Contato com Franqueado'), ('aguardando_acao', 'Aguardando Ação do Franqueado'), ('em_validacao', 'Em Validação'), ('resolvida', 'Resolvida')], default='pendente', max_length=30, verbose_name='Etapa da Resolução'),
        ),
    ]
