# Generated by Django 5.0.1 on 2026-01-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_resolution_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeauditissue',
            name='notification_channel',
            field=models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('notificacao', 'Notificação/Email'), ('ticket', 'Ticket'), ('telefone', 'Telefone'), ('presencial', 'Presencial')], max_length=20, null=True, verbose_name='Canal de Notificação'),
        ),
    ]
