# Generated by Django 5.0.1 on 2026-01-26 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_storeauditissue_notification_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeauditissue',
            name='auto_escalated',
            field=models.BooleanField(default=False, verbose_name='Escalonado Automaticamente'),
        ),
        migrations.AddField(
            model_name='storeauditissue',
            name='deadline_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Limite'),
        ),
        migrations.AddField(
            model_name='storeauditissue',
            name='deadline_hours',
            field=models.IntegerField(blank=True, help_text='24-48 horas para WhatsApp', null=True, verbose_name='Prazo em Horas'),
        ),
        migrations.AddField(
            model_name='storeauditissue',
            name='escalation_question_shown',
            field=models.BooleanField(default=False, verbose_name='Pergunta de Escalonamento Exibida'),
        ),
        migrations.AddField(
            model_name='storeauditissue',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID do Ticket'),
        ),
        migrations.AddField(
            model_name='storeauditissue',
            name='ticket_notes',
            field=models.TextField(blank=True, verbose_name='Observações do Ticket'),
        ),
        migrations.AddField(
            model_name='storeauditissue',
            name='ticket_priority',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=20, verbose_name='Prioridade do Ticket'),
        ),
        migrations.AddField(
            model_name='storeauditissue',
            name='ticket_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_responsible_issues', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Ticket'),
        ),
        migrations.AddField(
            model_name='storeauditissue',
            name='timer_ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Timer Encerrado Em'),
        ),
        migrations.AddField(
            model_name='storeauditissue',
            name='timer_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Timer Iniciado Em'),
        ),
        migrations.AlterField(
            model_name='storeauditissue',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('notificado_whatsapp', 'Notificado (WhatsApp)'), ('notificado_ticket', 'Notificado (Ticket)'), ('resolvida', 'Resolvida'), ('verificado', 'Verificado')], default='aberta', max_length=30),
        ),
        migrations.CreateModel(
            name='AnalystAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_target', models.IntegerField(default=1, help_text='Quantas vezes por semana deve auditar', verbose_name='Meta Semanal')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_assignments', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyst_assignments', to='core.store')),
            ],
            options={
                'verbose_name': 'Atribuição de Analista',
                'verbose_name_plural': 'Atribuições de Analistas',
                'ordering': ['analyst', 'store__code'],
                'unique_together': {('analyst', 'store')},
            },
        ),
    ]
