# Generated by Django 5.0.1 on 2026-01-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_notification_system_to_store_audits'),
    ]

    operations = [
        migrations.AddField(
            model_name='analystassignment',
            name='period_end',
            field=models.DateField(blank=True, null=True, verbose_name='Fim do Período'),
        ),
        migrations.AddField(
            model_name='analystassignment',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name='Início do Período'),
        ),
        migrations.AddField(
            model_name='store',
            name='suspension_reason',
            field=models.CharField(blank=True, choices=[('suspenso', 'Suspenso'), ('ponto', 'Ponto'), ('locacao', 'Locação'), ('implantacao', 'Implantação'), ('pausado', 'Pausado'), ('distrato', 'Distrato')], max_length=20, null=True, verbose_name='Motivo da Suspensão'),
        ),
    ]
