# Generated by Django 5.0.1 on 2026-01-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_add_periods_and_suspension_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeaudititem',
            name='cameras_recording',
            field=models.BooleanField(blank=True, null=True, verbose_name='Câmeras gravando?'),
        ),
        migrations.AddField(
            model_name='storeaudititem',
            name='cameras_recording_mode',
            field=models.CharField(blank=True, choices=[('movimento', 'Por Movimento'), ('continuo', 'Contínuo/24h')], max_length=20, null=True, verbose_name='Modo de gravação'),
        ),
    ]
