# Generated by Django 5.0.1 on 2026-02-05 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_storeaudititem_cameras_recording_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyVerificationKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(verbose_name='Início da Semana (Segunda)')),
                ('week_number', models.IntegerField(verbose_name='Número da Semana')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('total_assigned_stores', models.IntegerField(default=0, verbose_name='Lojas Atribuídas')),
                ('stores_verified', models.IntegerField(default=0, verbose_name='Lojas Verificadas')),
                ('total_audits_performed', models.IntegerField(default=0, verbose_name='Total de Auditorias')),
                ('goal_met', models.BooleanField(default=False, verbose_name='Meta Atingida')),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% de Conclusão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_kpis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KPI Semanal de Verificação',
                'verbose_name_plural': 'KPIs Semanais de Verificação',
                'ordering': ['-year', '-week_number'],
                'indexes': [models.Index(fields=['analyst', 'year', 'week_number'], name='core_weekly_analyst_fdc77c_idx'), models.Index(fields=['week_start_date'], name='core_weekly_week_st_892cfe_idx')],
                'unique_together': {('analyst', 'year', 'week_number')},
            },
        ),
    ]
