# Generated by Django 5.0.1 on 2026-02-05 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_weeklyverificationkpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAuditQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('daily_quota', models.IntegerField(default=0, verbose_name='Meta Diária')),
                ('audits_completed', models.IntegerField(default=0, verbose_name='Auditorias Realizadas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quota Diária de Auditoria',
                'verbose_name_plural': 'Quotas Diárias de Auditoria',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['analyst', 'date'], name='core_dailya_analyst_956f7c_idx'), models.Index(fields=['date'], name='core_dailya_date_ccc9f0_idx')],
                'unique_together': {('analyst', 'date')},
            },
        ),
    ]
