# Generated by Django 5.0.1 on 2026-02-06 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_dailyauditquota'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateField(verbose_name='Data do Atendimento')),
                ('id_conversa', models.CharField(max_length=200, verbose_name='ID da Conversa')),
                ('tipo_atendimento', models.CharField(choices=[('cliente', 'Cliente'), ('franqueado', 'Franqueado')], max_length=20)),
                ('apresentou_corretamente', models.BooleanField(default=True, verbose_name='1. Apresentou-se corretamente?')),
                ('erro_apresentacao', models.TextField(blank=True, verbose_name='Descrição do erro')),
                ('analisou_historico', models.BooleanField(default=True, verbose_name='2. Analisou o histórico?')),
                ('erro_historico', models.TextField(blank=True, verbose_name='Descrição do erro')),
                ('entendeu_solicitacao', models.BooleanField(default=True, verbose_name='3. Entendeu a solicitação do cliente/franqueado?')),
                ('erro_entendimento', models.TextField(blank=True, verbose_name='Descrição do erro')),
                ('informacao_clara', models.BooleanField(default=True, verbose_name='4. Passou a informação de forma clara?')),
                ('erro_informacao', models.TextField(blank=True, verbose_name='Descrição do erro')),
                ('acordo_espera', models.BooleanField(default=True, verbose_name='5. Realizou acordo de espera corretamente?')),
                ('erro_acordo_espera', models.TextField(blank=True, verbose_name='Descrição do erro')),
                ('atendimento_respeitoso', models.BooleanField(default=True, verbose_name='6. Realizou atendimento de forma respeitosa?')),
                ('erro_respeito', models.TextField(blank=True, verbose_name='Descrição do erro')),
                ('portugues_correto', models.BooleanField(default=True, verbose_name='7. Usou a língua portuguesa de forma correta?')),
                ('erro_portugues', models.TextField(blank=True, verbose_name='Descrição do erro')),
                ('finalizacao_correta', models.BooleanField(default=True, verbose_name='8. Realizou finalização do atendimento corretamente?')),
                ('erro_finalizacao', models.TextField(blank=True, verbose_name='Descrição do erro')),
                ('procedimento_correto', models.BooleanField(default=True, verbose_name='9. Seguiu o procedimento correto?')),
                ('erro_procedimento', models.TextField(blank=True, verbose_name='Descrição do erro')),
                ('pontuacao', models.IntegerField(default=0, verbose_name='Pontuação (0-9)')),
                ('nota', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Nota (0-10)')),
                ('classificacao', models.CharField(choices=[('excelente', 'Excelente'), ('bom', 'Bom'), ('regular', 'Regular'), ('insatisfatorio', 'Insatisfatório')], default='excelente', max_length=20, verbose_name='Classificação')),
                ('requer_acao', models.BooleanField(default=False, help_text='Marcado automaticamente quando nota está abaixo do percentual mínimo aceitável', verbose_name='Requer Ação (Alerta)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analista_auditado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Analista Auditado')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Auditor')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_atendimento', to='core.department')),
            ],
            options={
                'verbose_name': 'Auditoria de Atendimento',
                'verbose_name_plural': 'Auditorias de Atendimento',
                'ordering': ['-data_atendimento', '-created_at'],
                'indexes': [models.Index(fields=['analista_auditado', 'data_atendimento'], name='core_audito_analist_fd58d4_idx'), models.Index(fields=['department', 'data_atendimento'], name='core_audito_departm_55d8d0_idx'), models.Index(fields=['classificacao'], name='core_audito_classif_f7df94_idx'), models.Index(fields=['requer_acao'], name='core_audito_requer__5c525d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_minimo_aceitavel', models.DecimalField(decimal_places=2, default=77.78, help_text='Percentual mínimo de pontuação (0-100) para não gerar alerta. Padrão: 77.78% (7/9 critérios)', max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_auditoria', to='core.department')),
            ],
            options={
                'verbose_name': 'Configuração de Auditoria',
                'verbose_name_plural': 'Configurações de Auditoria',
                'unique_together': {('department',)},
            },
        ),
    ]
