# Generated by Django 5.0.1 on 2026-02-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auditoriaatendimento_configuracaoauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriaatendimento',
            name='imagem_evidencia_url',
            field=models.URLField(blank=True, help_text='Link da imagem armazenada no Supabase Storage', max_length=500, null=True, verbose_name='URL da Imagem de Evidência'),
        ),
    ]
