# Generated by Django 5.0.1 on 2026-02-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_add_image_url_auditoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoriaatendimento',
            name='imagem_evidencia_url',
        ),
        migrations.AddField(
            model_name='auditoriaatendimento',
            name='imagem_erro_acordo_espera',
            field=models.URLField(blank=True, help_text='URL da imagem no Supabase Storage', max_length=500, null=True, verbose_name='Evidência - Acordo de Espera'),
        ),
        migrations.AddField(
            model_name='auditoriaatendimento',
            name='imagem_erro_apresentacao',
            field=models.URLField(blank=True, help_text='URL da imagem no Supabase Storage', max_length=500, null=True, verbose_name='Evidência - Apresentação'),
        ),
        migrations.AddField(
            model_name='auditoriaatendimento',
            name='imagem_erro_entendimento',
            field=models.URLField(blank=True, help_text='URL da imagem no Supabase Storage', max_length=500, null=True, verbose_name='Evidência - Entendimento'),
        ),
        migrations.AddField(
            model_name='auditoriaatendimento',
            name='imagem_erro_finalizacao',
            field=models.URLField(blank=True, help_text='URL da imagem no Supabase Storage', max_length=500, null=True, verbose_name='Evidência - Finalização'),
        ),
        migrations.AddField(
            model_name='auditoriaatendimento',
            name='imagem_erro_historico',
            field=models.URLField(blank=True, help_text='URL da imagem no Supabase Storage', max_length=500, null=True, verbose_name='Evidência - Histórico'),
        ),
        migrations.AddField(
            model_name='auditoriaatendimento',
            name='imagem_erro_informacao',
            field=models.URLField(blank=True, help_text='URL da imagem no Supabase Storage', max_length=500, null=True, verbose_name='Evidência - Informação'),
        ),
        migrations.AddField(
            model_name='auditoriaatendimento',
            name='imagem_erro_portugues',
            field=models.URLField(blank=True, help_text='URL da imagem no Supabase Storage', max_length=500, null=True, verbose_name='Evidência - Português'),
        ),
        migrations.AddField(
            model_name='auditoriaatendimento',
            name='imagem_erro_procedimento',
            field=models.URLField(blank=True, help_text='URL da imagem no Supabase Storage', max_length=500, null=True, verbose_name='Evidência - Procedimento'),
        ),
        migrations.AddField(
            model_name='auditoriaatendimento',
            name='imagem_erro_respeito',
            field=models.URLField(blank=True, help_text='URL da imagem no Supabase Storage', max_length=500, null=True, verbose_name='Evidência - Respeito'),
        ),
    ]
