# Generated by Django 5.0.1 on 2026-02-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_add_individual_image_fields_per_criterion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriaatendimento',
            name='imagem_erro_acordo_espera',
            field=models.TextField(blank=True, help_text='URL ou dados base64 da imagem', null=True, verbose_name='Evidência - Acordo de Espera'),
        ),
        migrations.AlterField(
            model_name='auditoriaatendimento',
            name='imagem_erro_apresentacao',
            field=models.TextField(blank=True, help_text='URL ou dados base64 da imagem', null=True, verbose_name='Evidência - Apresentação'),
        ),
        migrations.AlterField(
            model_name='auditoriaatendimento',
            name='imagem_erro_entendimento',
            field=models.TextField(blank=True, help_text='URL ou dados base64 da imagem', null=True, verbose_name='Evidência - Entendimento'),
        ),
        migrations.AlterField(
            model_name='auditoriaatendimento',
            name='imagem_erro_finalizacao',
            field=models.TextField(blank=True, help_text='URL ou dados base64 da imagem', null=True, verbose_name='Evidência - Finalização'),
        ),
        migrations.AlterField(
            model_name='auditoriaatendimento',
            name='imagem_erro_historico',
            field=models.TextField(blank=True, help_text='URL ou dados base64 da imagem', null=True, verbose_name='Evidência - Histórico'),
        ),
        migrations.AlterField(
            model_name='auditoriaatendimento',
            name='imagem_erro_informacao',
            field=models.TextField(blank=True, help_text='URL ou dados base64 da imagem', null=True, verbose_name='Evidência - Informação'),
        ),
        migrations.AlterField(
            model_name='auditoriaatendimento',
            name='imagem_erro_portugues',
            field=models.TextField(blank=True, help_text='URL ou dados base64 da imagem', null=True, verbose_name='Evidência - Português'),
        ),
        migrations.AlterField(
            model_name='auditoriaatendimento',
            name='imagem_erro_procedimento',
            field=models.TextField(blank=True, help_text='URL ou dados base64 da imagem', null=True, verbose_name='Evidência - Procedimento'),
        ),
        migrations.AlterField(
            model_name='auditoriaatendimento',
            name='imagem_erro_respeito',
            field=models.TextField(blank=True, help_text='URL ou dados base64 da imagem', null=True, verbose_name='Evidência - Respeito'),
        ),
    ]
