# Generated by Django 5.0.1 on 2026-02-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_add_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyauditquota',
            name='extra_quota',
            field=models.IntegerField(default=0, verbose_name='Quota Extra'),
        ),
    ]
