# Generated by Django 5.0.1 on 2026-02-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_dailyauditquota_extra_quota'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(verbose_name='Mensagem Resumida')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Detalhes Completos (HTML)')),
                ('category', models.CharField(choices=[('system', 'Melhoria do Sistema'), ('event', 'Evento'), ('news', 'Novidade'), ('alert', 'Alerta')], default='system', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Notificação do Sistema',
                'verbose_name_plural': 'Notificações do Sistema',
                'ordering': ['-created_at'],
            },
        ),
    ]
