# Generated by Django 5.1.15 on 2026-02-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_performance_composite_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriaatendimento',
            name='ciente_analista',
            field=models.BooleanField(default=False, help_text='Marcado pelo analista ao reconhecer a auditoria', verbose_name='Ciente pelo Analista'),
        ),
        migrations.AddField(
            model_name='auditoriaatendimento',
            name='data_ciente',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Ciente'),
        ),
    ]
