# Generated by Django 5.1.2 on 2026-02-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auditoriaatendimento_ciente_analista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriaatendimento',
            name='link_conversa',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link da Conversa'),
        ),
    ]
