# Generated by Django 5.1.2 on 2026-02-25 16:22

from django.db import migrations


def create_rh_department(apps, schema_editor):
    Department = apps.get_model('core', 'Department')
    Department.objects.get_or_create(
        name='RH',
        defaults={'slug': 'rh', 'description': 'Departamento de Recursos Humanos'}
    )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_storeaudit_performance_indexes'),
    ]

    operations = [
        migrations.RunPython(create_rh_department),
    ]
