# Generated by Django 5.1.2 on 2026-02-25 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_create_rh_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatInactivityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100)),
                ('chat_link', models.URLField(max_length=500)),
                ('chat_date', models.DateField()),
                ('was_inactivity', models.BooleanField(default=True, verbose_name='Foi inatividade?')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitação de Inatividade',
                'verbose_name_plural': 'Solicitações de Inatividade',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='analystassignment',
            name='core_analystass_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeaudit',
            name='core_storaud_analyst_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeaudit',
            name='core_storaud_store_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeauditissue',
            name='core_storaudiss_status_idx',
        ),
        migrations.AddField(
            model_name='chatinactivityrequest',
            name='analyst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_inactivity_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatinactivityrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_chat_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
