# Generated by Django 5.1.2 on 2026-02-26 20:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_chatinactivityrequest_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='analystassignment',
        #     name='active',
        #     field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        # ),
        # migrations.AlterField(
        #     model_name='storeaudit',
        #     name='created_at',
        #     field=models.DateTimeField(auto_now_add=True, db_index=True),
        # ),
        # migrations.AlterField(
        #     model_name='storeauditissue',
        #     name='created_at',
        #     field=models.DateTimeField(auto_now_add=True, db_index=True),
        # ),
        # migrations.AlterField(
        #     model_name='storeauditissue',
        #     name='status',
        #     field=models.CharField(choices=[('aberta', 'Aberta'), ('notificado_whatsapp', 'Notificado (WhatsApp)'), ('notificado_ticket', 'Notificado (Ticket)'), ('resolvida', 'Resolvida'), ('verificado', 'Verificado')], db_index=True, default='aberta', max_length=30),
        # ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('salario_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='core.department')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.TextField(blank=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email_pessoal', models.EmailField(blank=True, max_length=254)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='colaboradores_fotos/')),
                ('data_admissao', models.DateField()),
                ('data_desligamento', models.DateField(blank=True, null=True)),
                ('salario_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_contrato', models.CharField(choices=[('clt', 'CLT'), ('pj', 'PJ'), ('estagio', 'Estágio'), ('temporario', 'Temporário')], default='clt', max_length=20)),
                ('jornada_trabalho', models.CharField(blank=True, help_text='Ex: 44h semanais, 10h às 19h', max_length=100)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('ferias', 'Férias'), ('afastado', 'Afastado'), ('desligado', 'Desligado')], default='ativo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo_atual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='core.cargo')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores_rh', to='core.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_evento', models.DateField(default=django.utils.timezone.now)),
                ('tipo_evento', models.CharField(choices=[('admissao', 'Admissão'), ('promocao', 'Promoção'), ('aumento_salarial', 'Alteração Salarial'), ('mudanca_funcao', 'Mudança de Função'), ('mudanca_departamento', 'Mudança de Departamento'), ('desligamento', 'Desligamento')], max_length=30)),
                ('salario_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salario_novo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cargo_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_anterior', to='core.cargo')),
                ('cargo_novo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_novo', to='core.cargo')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.colaborador')),
            ],
            options={
                'verbose_name': 'Histórico Profissional',
                'verbose_name_plural': 'Históricos Profissionais',
                'ordering': ['-data_evento'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('feedback', 'Feedback'), ('pdi', 'Plano de Desenvolvimento (PDI)'), ('treinamento', 'Treinamento Realizado'), ('avaliacao_anual', 'Avaliação de Desempenho')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('comentarios', models.TextField()),
                ('proximos_passos', models.TextField(blank=True, verbose_name='Plano de Ação / Próximos Passos')),
                ('nota_quantitativa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avaliador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='core.colaborador')),
            ],
            options={
                'verbose_name': 'Registro de Performance',
                'verbose_name_plural': 'Registros de Performance',
                'ordering': ['-data_registro'],
            },
        ),
    ]
