# Generated by Django 5.1.2 on 2026-02-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_analystassignment_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analystassignment',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cargo_atual',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicoprofissional',
            name='cargo_anterior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicoprofissional',
            name='cargo_novo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='storeaudit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='storeauditissue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='storeauditissue',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('notificado_whatsapp', 'Notificado (WhatsApp)'), ('notificado_ticket', 'Notificado (Ticket)'), ('resolvida', 'Resolvida'), ('verificado', 'Verificado')], db_index=True, default='aberta', max_length=30),
        ),
    ]
